### ISSUE TITLE
[BUG]Cannot find PyTorch

### ISSUE THREAD

**Issue by dreammu** [Dadangdut33/Speech-Translate#14]
**Describe the bug**
I'm using Python 3.8.10 on Windows which installed the GPU version of PyTorch, but it shows me that "None of PyTorch, TensorFlow >= 2.0, or Flax have been found".

**To Reproduce**
1. Run the program
2. On CLI it shows "None of PyTorch, TensorFlow >= 2.0, or Flax have been found"
3. When recording sound or importing file, it will download and use the CPU version of PyTorch

**Expected behavior**
It can detect PyTorch existed on my system.

**Screenshots**
![image](https://user-images.githubusercontent.com/84692291/218324163-09b37b69-793e-4deb-a7f1-63ff16d81362.png)
![image](https://user-images.githubusercontent.com/84692291/218324198-b5404f9d-89b9-4157-9952-9e9d43b6e548.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Python Version 3.8.10

**Additional context**
I guess maybe it is because different versions of Python are used? I don't know:(

**Comment by Dadangdut33** [comment]
Hmm have you tried downgrading the pytorch version? Is your gpu cuda compatible?

**Comment by Dadangdut33** [comment]
I tried to recreate this bug on my local but there seems to be no problem?. It might be that your gpu is not cuda compatible.

and about the python version, i recommend that you use pyenv to easily manage or switch your python version.

**Comment by dreammu** [comment]
I didn't try to downgrade my PyTorch version but it can be correctly called by Whisper, so CUDA should be compatible.

**Comment by dreammu** [comment]
Ok, after I re-extract the release file it seems to work properly... I don't know what made it go wrong. Thank you for your answering!
