### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by DavorZg** [Dadangdut33/Speech-Translate#18]
After running the application I get issue: FileNotFoundError: [WinError 2] The system cannot find the file specified

![image](https://user-images.githubusercontent.com/80821070/223071583-fa45ef4c-b615-48eb-ba2b-7a679e194e43.png)

**Comment by Dadangdut33** [comment]
This is same as #12 you will need to install ffmpeg first to fix this.

Here are the instructions for automatic installation:
```
# on Ubuntu or Debian
sudo apt update && sudo apt install ffmpeg

# on Arch Linux
sudo pacman -S ffmpeg

# on MacOS using Homebrew (https://brew.sh/)
brew install ffmpeg

# on Windows using Chocolatey (https://chocolatey.org/)
choco install ffmpeg

# on Windows using Scoop (https://scoop.sh/)
scoop install ffmpeg
```

alternatively you can download it and add it to your system PATH manually

**Comment by DavorZg** [comment]
Thank you
