### ISSUE TITLE
[BUG] Detected as virus

### ISSUE THREAD

**Issue by k566o** [Dadangdut33/Speech-Translate#21]
Kaspersky see's latest release as a virus
![2023-03-23 11_41_17-AlertWindow](https://user-images.githubusercontent.com/98302826/227078758-c9d0217a-bf8b-4517-8baf-2d2bc9d3b32b.png)

**Comment by Dadangdut33** [comment]
I'm 100% sure that is false positive, if you are unsure you can compile it yourself or run it from the source code directly

**Comment by k566o** [comment]
Hi, I submitted a case to Kaspersky. They will likely confirm the false positive and update their database

**Comment by Dadangdut33** [comment]
Thanks!
