### ISSUE TITLE
how to set transcription language

### ISSUE THREAD

**Issue by TingTingin** [Dadangdut33/Speech-Translate#23]
Is there a way to set the transcription language?

**Comment by Dadangdut33** [comment]
There should be a combobox for it on the top section of the main window like on this image

![image](https://user-images.githubusercontent.com/57717531/227759128-e15da4ce-8c28-4c64-93d7-a5432736fc8d.png)


The `from` combobox is for the transcription language / source language of the input
The `to` combobox is for the translation target / what you want to translate into
