### ISSUE TITLE
failure to run main.py

### ISSUE THREAD

**Issue by MRAWAY77** [Dadangdut33/Speech-Translate#3]
Successfully install the env and build.spec... is there something i miss out in the readME.md?
Im using ubuntu 20.04

 python Main.py 
Traceback (most recent call last):
  File "Main.py", line 27, in <module>
    from speech_translate.Globals import app_icon, app_icon_missing, app_name, fJson, gClass
  File "/home/mraway/Desktop/src/Speech-Translate/speech_translate/Globals.py", line 16, in <module>
    from .utils.Json import SettingJsonHandler
  File "/home/mraway/Desktop/src/Speech-Translate/speech_translate/utils/Json.py", line 7, in <module>
    from speech_translate.components.MBox import Mbox
  File "/home/mraway/Desktop/src/Speech-Translate/speech_translate/components/MBox.py", line 10, in <module>
    def Mbox(title: str, text: str, style: Literal[0, 1, 2, 3], parent: Tk | None = None):
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

![Screenshot from 2022-12-20 17-50-50](https://user-images.githubusercontent.com/37066888/208637258-3f03562d-14d9-4863-8623-97f6e0ce3695.png)

**Comment by Dadangdut33** [comment]
hmm  You are using python 3.8.5 and it seems that [`|` operator is added in python 3.10](https://github.com/tiangolo/typer/issues/371#issuecomment-1073649190).

I will add add that to the requirements.

**Comment by Dadangdut33** [comment]
Let me know if it's still not working, thanks for the issue that you submitted :D

**Comment by MRAWAY77** [comment]
Hi Thanks! the updates work for linux now. Do you happen to know if i can batch upload multiple files and process it together?

**Comment by Dadangdut33** [comment]
> Hi Thanks! the updates work for linux now. Do you happen to know if i can batch upload multiple files and process it together?

That's one of the feature that is gonna be implemented for this app, but I'm a little busy now so it might take a while. You can post it on issue as a feature request if you want @MRAWAY77
