### ISSUE TITLE
When importing multiple audio files, the output file names are mixed up [BUG]

### ISSUE THREAD

**Issue by Corvalan** [Dadangdut33/Speech-Translate#32]
**Describe the bug**
When importing multiple audio files, the output files are named wrongly.
The title of one audio file is included in the title of another output file of another audio file of the list.

**Comment by Dadangdut33** [comment]
i'm really sorry for the late reply, can you elaborate more? i tried to replicate it in latest dev branch but could not seem to get the bug. 

Also i'll be adding an option to format the output file later

**Comment by Dadangdut33** [comment]
closed because of no response. Feel free to reopen if you may provide more information
