### ISSUE TITLE
The first minute of some of the audio transcriptions is missing [BUG]

### ISSUE THREAD

**Issue by Corvalan** [Dadangdut33/Speech-Translate#33]
The first minute of some of the audio transcriptions is missing. 
This happens when I upload multiple audio files to be transcribed.
I'm not sure what causes this, since the audio quality of the first minute is as clear as the rest of the audio.
I use the CPU version on a small laptop, so it may be that because of the processor limitations, and me working on the same laptop with another application, this results in loss of information during the transcription. I will test this with another, stronger PC.
Anyhow, there is no warning or indication that there is data loss or transcription issues. Is there a way for the program to check this in real time?

**Comment by Dadangdut33** [comment]
can you help giving me some sample for it? so that i can replicate the bug

> Anyhow, there is no warning or indication that there is data loss or transcription issues. Is there a way for the program to check this in real time?

Hmm, this might actually be possible, i could maybe try splitting up the file input into little pieces. I'm gonna have to think about this first
