### ISSUE TITLE
[BUG] Chinese tradional is not supported on TL Engline: Google

### ISSUE THREAD

**Issue by SugarQuiet** [Dadangdut33/Speech-Translate#34]
**Describe the bug**
Chinese traditional is not supported on TL Engline: Google

**Screenshots**
![image](https://user-images.githubusercontent.com/21107283/233752827-74511aa2-7bca-4818-b8b1-1897333fa72d.png)

**Comment by k566o** [comment]
I noticed that too. You can use auto detect for the language and it will translate it , problem is I am trying to use it on bilingual live stream, where both Chinese and English is being spoken. I understand English, so don't need it for that, but it seems when it detects English and starts transcribing that it can cause a big pause before it returns to translating the Chinese. And during that pause the Chinese may never get translated, not even late.

**Comment by Dadangdut33** [comment]
sorry for the late reply, there seems to be a small bug in the langauge code that caused all that error

**Comment by Dadangdut33** [comment]
Fixed in 1.3.0 release
