### ISSUE TITLE
[REQ] Copy to clipboard button

### ISSUE THREAD

**Issue by MirkoPMC** [Dadangdut33/Speech-Translate#36]
**Is your feature request related to a problem? Please describe.**
Since I usually want to place the text in another window I need to select the entire text and copy it manually.

**Describe the solution you'd like**
It would be great to have a copy to clipboard button of the current text in the box.

**Comment by Dadangdut33** [comment]
great idea! i will add it

**Comment by Dadangdut33** [comment]
Added in 1.3.0 release
