### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by morrellaberdeen** [Dadangdut33/Speech-Translate#37]
I imported a small english audio file for the purpose of translating into spanish. My choice of translation engine was google. I keep receiving this error a few seconds into the process: ERROR   - byte indices must be integers or slices, not str

**Comment by Dadangdut33** [comment]
sorry for the late reply, can you add more details. maybe showing me the log of the program

**Comment by Dadangdut33** [comment]
i'll close this for now, you can open it again and tell me the details when you feel like it
