### ISSUE TITLE
[BUG] Export Folder location never visually updates in Settings, despite changing to a new location

### ISSUE THREAD

**Issue by ch826** [Dadangdut33/Speech-Translate#39]
Under Speech Translate > View > Settings > Export > Export Folder

When I change the Export folder, internally, the program properly changes the Export folder (which is good), but visually, in the Export Folder section of Settings, the directory name never changes.  It continues to show the default Export Folder directory that originally was there.

This is a very minor (visual) bug that does not affect the functionality of the program.

**Comment by Dadangdut33** [comment]
Fixed in 1.3.0 release
