### ISSUE TITLE
[BUG] can't get the input devices when the program start

### ISSUE THREAD

**Issue by IcarusAegis** [Dadangdut33/Speech-Translate#41]
when i start the program download from realsase(the latest),it said 
2023-08-03 14:01:35,349 ERROR   - Something went wrong while trying to get the input devices (mic). (Record.py:56) [MainThread]
2023-08-03 14:01:35,350 ERROR   - 'utf-8' codec can't decode byte 0xc2 in position 6: invalid continuation byte (Record.py:57) 
![image](https://github.com/Dadangdut33/Speech-Translate/assets/46650308/859538db-3454-4b24-9f11-d7ead56e3ba2)
![image](https://github.com/Dadangdut33/Speech-Translate/assets/46650308/18668c98-cfc2-4d97-b97c-72d79f60db20)

the program should recognize my mic,it's useable in other applications and it's fine in windows.
Buzz and whisper-desktop can recognize my mic and it's useable.

![image](https://github.com/Dadangdut33/Speech-Translate/assets/46650308/db76edcc-bf03-4215-95df-d560a95a62fe)

 - OS: windows 11 22H2
 - cpu 7840s with 4060
 - a laptop with the mic bulit in

**Comment by Dadangdut33** [comment]
seems to be related with the sounddevice library. Maybe i'll switch the device querying to pyaudio or add it as a fallback option

**Comment by IcarusAegis** [comment]
> seems to be related with the sounddevice library. Maybe i'll switch the device querying to pyaudio or add it as a fallback option

thank you，I will waiting for the new release.

**Comment by IcarusAegis** [comment]
@Dadangdut33 I tried dev version ,now it is working well ,this bug fixed.
