### ISSUE TITLE
Fix Character limit per line

### ISSUE THREAD

**Issue by LearningJer** [Dadangdut33/Speech-Translate#44]
It's entirely possible I overlooked it but, is there a way to set a custom character limit per line? I am trying to have just a single line with a max of 18 characters per sentence.

Edit*
This is for the audio transcriptions

**Comment by Dadangdut33** [comment]
there is no setting for that. But i'll add it now, thanks for the suggestion 👍

**Comment by LearningJer** [comment]
Thanks for updating this! Though I am not sure it is what I meant that was updated. I was hoping for something similar to this?
https://youtu.be/GIh9imtq-fI?si=x0XQhHYWHevsUTg0&t=98

Where the user would be able to set the max character limit per line on a transcribed audios subtitle track. Unless I missed something again in this latest patch. Thanks again!

**Comment by Dadangdut33** [comment]
whoops, it seems that at some point the whole character limit was broken.

I added it for the record session and it should have worked like this
![image](https://github.com/Dadangdut33/Speech-Translate/assets/57717531/caa64a15-31c6-47a5-9838-b9a3799c9d39)

I also noticed that it is possible to limit it for the file import using [split_by_length()](https://github.com/jianfch/stable-ts/blob/main/stable_whisper/result.py#L1089-L1120), i guess i will add it too in the next release alongside the bug fix. 

Thanks for letting me know of this bug
