### ISSUE TITLE
[BUG] GUI app: Standard whisper (including the new large-v3) does not work.

### ISSUE THREAD

**Issue by Adi900696** [Dadangdut33/Speech-Translate#53]
Problem with GUI application. Standard whisper (including the new large-v3) does not work on CPU and CUDA. Only faster-whisper works. The computer freezes, fills the RAM to 100% (Also using lightweight models e.g. tiny.en) and also the paging file, which even causes the NVMe SSD disk to be used at 100%. When it comes to logs, it is difficult to remove because the computer hangs and the log itself weighs as much as 1 GB after forcefully killing the application. Notepad can't even open it (big size file). Faster-whisper works properly.
![Zrzut ekranu 2023-11-09 212759](https://github.com/Dadangdut33/Speech-Translate/assets/150326137/5426cc9c-adae-4154-81fa-abc738159bd6)
![Zrzut ekranu 2023-11-09 213827](https://github.com/Dadangdut33/Speech-Translate/assets/150326137/a666dba5-b4aa-440f-b2c5-0e22e38dc773)

**Comment by Dadangdut33** [comment]
hmm that's weird, i also found that happening, thanks for reporting

**Comment by Dadangdut33** [comment]
i finally checked it and found out that the problem is because the metadata of whisper is not copied into the lib folder and there seems to be some logic error in the logging, thanks for reporting this bug, it should be gone in next release

**Comment by Dadangdut33** [comment]
Fixed, thanks for the bug report
