### ISSUE TITLE
On light themes, text in the context menu in the dynamic text field is not visible [BUG]

### ISSUE THREAD

**Issue by Adi900696** [Dadangdut33/Speech-Translate#54]
On light themes, text in the context menu in the dynamic text field is not visible.

Only white text:

![bug light theme](https://github.com/Dadangdut33/Speech-Translate/assets/150326137/cc0d4570-d686-4ac4-a618-300921120f3b)

On dark theme is ok:

![in dark theme is ok](https://github.com/Dadangdut33/Speech-Translate/assets/150326137/cb499036-5002-4552-b899-a860932dd7aa)

**Comment by Dadangdut33** [comment]
oh wow i didn't notice, thanks for reporting it
