### ISSUE TITLE
[REQ] Add option for no max sentences limit

### ISSUE THREAD

**Issue by sherkhan30452** [Dadangdut33/Speech-Translate#57]
**Describe the bug**
When I am live transcribing audio from speaker when recording, the first transcribe sentence disappears after some duration, therefore unable to export all transcribed text (into .txt) from the software. In short, main window acting as subtitle window which should not happen when recording as transcribed text from live audio should be kept from start to end in the main video for exporting into (.txt).

**To Reproduce**
1. (For this setup) Open this youtube video in your browser https://www.youtube.com/watch?v=02E2WgRcHpo (Note: video duration 1 min 20 sec)
2. Pause the youtube video
3. Set task to transcribe, Input to speaker and then Start recording.
4. Play the Youtube video till the end. (You will see that the CPU speech-translator has perfectly transcribed the video from starting, however when you reach the end of the youtube video, previous first line is deleted.

**Expected behavior**
All transcribed text must remain from the start till end in the main window, (until the user manually press the 'Clear' button.)

**Desktop (please complete the following information):**
 - OS: Edition	Windows 10 Home Single Language
Version	22H2
Installed on	‎04/‎08/‎23
OS build	19045.3803
Experience	Windows Feature Experience Pack 1000.19053.1000.0

 - Python Version: 3.11.5

**Comment by Dadangdut33** [comment]
That is the intended behaviour actually. There is a limit that you can set per session as to how many sentences there are shown and stored in the memory when recording

![image](https://github.com/Dadangdut33/Speech-Translate/assets/57717531/f0ea55c4-0bb9-4312-89d4-abf8593929ed)

I set the limit to 100 in the app. I suppose you want an option for it to be limitless?

**Comment by sherkhan30452** [comment]
> I suppose you want an option for it to be limitless?
Yes. (Like Windows Dictate or Google Doc dictate.) Keep the text, let the user decides what to do with the transcribed text.

**Comment by Dadangdut33** [comment]
I see, alright i'll get to it, thanks for suggestion/request

**Comment by sherkhan30452** [comment]
Thank you so much 😀!

**Comment by Dadangdut33** [comment]
i have added it in the 1.3.7 release, thanks for the request/suggestion 👍
