### ISSUE TITLE
Mic issue for real time transcription.

### ISSUE THREAD

**Issue by MRAWAY77** [Dadangdut33/Speech-Translate#6]
![Screenshot from 2023-01-06 11-44-05](https://user-images.githubusercontent.com/37066888/210925927-7a042a9c-65ae-4af3-b423-1ebf74964c54.png)

it seems like the RT transcription faces some issue after the git pull patches?

**Comment by Dadangdut33** [comment]
You sure that's the latest commit? It's a typo that should have been fixed already

**Comment by MRAWAY77** [comment]
hmm it should be because i git pull from master branch and it can perform batch processing...

**Comment by Dadangdut33** [comment]
> hmm it should be because i git pull from master branch and it can perform batch processing...

Please confirm by doing git fetch and git pull because it is already fixed in [this commit](https://github.com/Dadangdut33/Speech-Translate/commit/38fae7ceefd3dc1bc603efebb9b250dc0dacce1d)
