### ISSUE TITLE
for some reason , it is not starting 

### ISSUE THREAD

**Issue by fireheart2008** [Dadangdut33/Speech-Translate#62]
the program does not open 
version 1.3.7 cpu only

11th Gen Intel(R) Core(TM) i3-1125G4 @ 2.OOGHz 2.00 GHz
16.0 GB (15.8 GB usable)
Windows 11 Pro
23H2
22631.2861

**Comment by Dadangdut33** [comment]
thanks for reporting, i might have found the problem. Will release an update asap

**Comment by Dadangdut33** [comment]
i have release a new version https://github.com/Dadangdut33/Speech-Translate/tree/1.3.8. Please do check it out. 

you can open this issue again if the problem still persist
