### ISSUE TITLE
release 1.3. CPU only cant find "small" module

### ISSUE THREAD

**Issue by JeremyWongJW** [Dadangdut33/Speech-Translate#63]
I tried release 1.3. CPU only and got into this issue

![图片](https://github.com/Dadangdut33/Speech-Translate/assets/50523392/08b69ad9-9d56-451d-aec0-0e88b6117d47)

I follow the instruction to download the module and success, but the above issue just keep coming up. It seems it cant find the "small" module. Is there any solution?

**Comment by Dadangdut33** [comment]
Can you please elaborate more

what version is it 1.3.xx ? 
have you tried pressing ok and letting it download the model until its done?

**Comment by JeremyWongJW** [comment]
1.3.8, the latest one.
i follow the instruction to download the module and it's done.but it keeps telling me the module not found


> Can you please elaborate more
> 
> what version of 1.3 is it? have you tried pressing ok and letting it download the model until its done?

**Comment by Dadangdut33** [comment]
ok, i think i found the problem. Will release a patch asap

**Comment by Dadangdut33** [comment]
it should be fixed now, thanks for reporting the bug 👍
